### ISSUE TITLE
CukePlugin not working with gradle-1.0-milestone-1

### ISSUE THREAD

**Issue by dokipen** [RobertFischer/gradle-plugins#11]
I get the following error when enabling it:

```
* What went wrong:
A problem occurred evaluating root project 'embedly-java'.
Cause: Could not find property 'classes' on root project 'embedly-java'.


* Exception is:
org.gradle.api.LocationAwareGradleScriptException: Build file '/home/doki_pen/src/embedly-java/build.gradle' line: 2
A problem occurred evaluating root project 'embedly-java'.
at org.gradle.groovy.scripts.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:51)
at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:127)
at org.gradle.configuration.BuildScriptProcessor.evaluate(BuildScriptProcessor.java:38)
at org.gradle.configuration.DefaultProjectEvaluator.evaluate(DefaultProjectEvaluator.java:38)
at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:506)
at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:71)
at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:23)
at org.gradle.configuration.ProjectEvaluationConfigurer.execute(ProjectEvaluationConfigurer.java:21)
at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuildConfigurer.java:38)
at org.gradle.configuration.DefaultBuildConfigurer$1.execute(DefaultBuildConfigurer.java:36)
at org.gradle.api.internal.project.AbstractProject.configure(AbstractProject.java:482)
at org.gradle.api.internal.project.AbstractProject.allprojects(AbstractProject.java:477)
at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:35)
at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:136)
at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:107)
at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:75)
at org.gradle.launcher.RunBuildAction.execute(RunBuildAction.java:41)
at org.gradle.launcher.RunBuildAction.execute(RunBuildAction.java:27)
at org.gradle.launcher.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory.java:209)
at org.gradle.launcher.CommandLineActionFactory$WithLoggingAction.execute(CommandLineActionFactory.java:193)
at org.gradle.launcher.Main.execute(Main.java:55)
at org.gradle.launcher.Main.main(Main.java:40)
at org.gradle.launcher.ProcessBootstrap.runNoExit(ProcessBootstrap.java:46)
at org.gradle.launcher.ProcessBootstrap.run(ProcessBootstrap.java:28)
at org.gradle.launcher.GradleMain.main(GradleMain.java:24)
Caused by: groovy.lang.MissingPropertyException: Could not find property 'classes' on root project 'embedly-java'.
at org.gradle.api.internal.AbstractDynamicObject.propertyMissingException(AbstractDynamicObject.java:43)
at org.gradle.api.internal.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:35)
at org.gradle.api.internal.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:54)
at org.gradle.api.internal.project.DefaultProject_Decorated.getProperty(Unknown Source)
at com.smokejumperit.gradle.CukePlugin.apply(CukePlugin.groovy:113)
at com.smokejumperit.gradle.CukePlugin.apply(CukePlugin.groovy)
at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.providePlugin(DefaultProjectsPluginContainer.java:103)
at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.addPluginInternal(DefaultProjectsPluginContainer.java:67)
at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.apply(DefaultProjectsPluginContainer.java:41)
at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:90)
at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$100(DefaultObjectConfigurationAction.java:32)
at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$2.run(DefaultObjectConfigurationAction.java:63)
at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:114)
at org.gradle.api.internal.project.AbstractProject.apply(AbstractProject.java:873)
at org.gradle.api.Project$apply.call(Unknown Source)
at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:35)
at org.gradle.api.Script$apply.callCurrent(Unknown Source)
at build_29ptjevrjg9mm4gmcqdli1pl5f.run(/home/doki_pen/src/embedly-java/build.gradle:2)
at org.gradle.groovy.scripts.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:49)
... 24 more
```

**Comment by RobertFischer** [comment]
Try 0.7.1-SNAPSHOT.  Let me know if that fixes it for you.

**Comment by dokipen** [comment]
Can you also try changing the cuke4duke version to 0.4.3?  http://cukes.info/maven/cuke4duke/cuke4duke/

**Comment by dokipen** [comment]
or just pull ck's patch, I think it bumps the cuke4duke version

**Comment by RobertFischer** [comment]
Done.  Also deployed another new snapshot.

**Comment by dokipen** [comment]
The fix works, but it's not pushed to your maven repo.  I had to build manually to test.  Also, you have this error, but it doesn't stop the build so it's low priority:

  unknown resolver MavenCentral (via CukePlugin)

Sorry I don't know more about gradle or I'd fix it.

**Comment by RobertFischer** [comment]
You can ignore "unknown resolver" messages.  They're an artifact of Ivy module caching, and probably should be suppressed by Gradle.

Pushed again to the Maven repo.  Not sure what was up with that.

**Comment by dokipen** [comment]
May have been my bad.  I don't think it was pulling the new one.  Thanks for all the work.  Any idea where cuke looks for step definitions?

**Comment by goober** [comment]
I get the same error when I try to run the plugin using grade-1.0-milestone-3.

"A problem occurred evaluating root project 'sample'.
Cause: Could not find property 'classes' on task container."

`apply plugin:com.smokejumperit.gradle.CukePlugin
buildscript {
    repositories {
      mavenRepo urls:'http://repo.smokejumperit.com'
    }
    dependencies {
      classpath 'com.smokejumperit:gradle-plugins:0.8.2'
    }
  }
task check << {
  logger.info("Things seem to be working!")
}`
