### ISSUE TITLE
RunJRuby does not work with latest gradle (at least >=m4)

### ISSUE THREAD

**Issue by jeppenejsum** [RobertFischer/gradle-plugins#20]
I get a NCDFE:

13:08:46.823 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NoClassDefFoundError: com.google.common.collect.MapMaker
13:08:46.824 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.ClassLoadersPlugin.class$(ClassLoadersPlugin.groovy)
13:08:46.824 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.ClassLoadersPlugin.$get$$class$com$google$common$collect$MapMaker(ClassLoadersPlugin.groovy)
13:08:46.824 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.ClassLoadersPlugin.apply(ClassLoadersPlugin.groovy:13)
13:08:46.825 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.ClassLoadersPlugin.apply(ClassLoadersPlugin.groovy)
13:08:46.825 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.providePlugin(DefaultProjectsPluginContainer.java:107)
13:08:46.826 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.addPluginInternal(DefaultProjectsPluginContainer.java:71)
13:08:46.826 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultProjectsPluginContainer.apply(DefaultProjectsPluginContainer.java:41)
13:08:46.827 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:90)
13:08:46.830 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$100(DefaultObjectConfigurationAction.java:32)
13:08:46.830 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$2.run(DefaultObjectConfigurationAction.java:63)
13:08:46.830 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:114)
13:08:46.831 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.internal.project.AbstractProject.apply(AbstractProject.java:845)
13:08:46.831 [ERROR] [org.gradle.BuildExceptionReporter]    at org.gradle.api.Project$apply$0.call(Unknown Source)
13:08:46.831 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin.apply(RunJRubyPlugin.groovy:12)
13:08:46.832 [ERROR] [org.gradle.BuildExceptionReporter]    at com.smokejumperit.gradle.RunJRubyPlugin.apply(RunJRubyPlugin.groovy)

Haven't looked into the underlying reasons yet....

**Comment by jeppenejsum** [comment]
Tried with m6 and get the same error.

A workaround is to add     classpath 'com.google.guava:guava:10.0.1'
 to the build script dependencies.

Dunno why this used to work? Was the lib included on the gradle classpath somehow?
